### ISSUE TITLE
error standardizing ionization

### ISSUE THREAD

**Issue by remov3** [mcs07/MolVS#15]
Using the following SMILES string, i have encountered the following error:

USED SMILES: 

    standardize_smiles('[Na].[Na].O[Se](O)=O')

OUTPUT:
log.info('Ionizing %s to balance previous charge corrections', self.acid_base_pairs[ppos].name)
TypeError: tuple indices must be integers or slices, not NoneType

The command works with this SMILES

    O=[Se]([O-])[O-].[Na+].[Na+]

Thank you in advance

**Comment by hsiaoyi0504** [comment]
Maybe it's part of the issue of [rdkit](https://github.com/rdkit/rdkit), but I actually think the problem is that your input SMILES is non-sense and it can't be the issue of MolVS. Do you now which version of rdkit you use? I can't read both cases through rdkit.
