### ISSUE TITLE
A Error when doing the example

### ISSUE THREAD

**Issue by ifyoungnet** [mcs07/MolVS#3]
Thank you for providing this good package. But I have encountered a Error when I am running the example (Standardize)
#########################################
 rdkit.Chem.rdmolfiles.MolFromSmiles(unicode)
did not match C++ signature:
    MolFromSmiles(std::string SMILES, bool sanitize=True, boost::python::dict replacements={})

##########################################

Because of the "Chem.MolFromSmarts('[CX3](=O)[OX2H1]')" need a string. While ''from __future__ import unicode_literals" was added at the top .

If I remove the "from __future__ import unicode_literals". Things goes well.

Could you please explain how to avoid this error? or this "from __future__ import unicode_literals" is used in the other latter code? Can I just remove it?

**Comment by mcs07** [comment]
What version of RDKit do you have installed? I thought this issue had been fixed since 2013 (see https://github.com/rdkit/rdkit/issues/179).

**Comment by ifyoungnet** [comment]
Thank you for your reply. I am using a rdkit(201309-1) from Ubuntu. It is not convenient for me to change the version because other projects relies on it. Can I just remove the "from future import unicode_literals"?

**Comment by mcs07** [comment]
Yes I think removing the future import should be fine. The main reason it is used is to ensure consistent behaviour across python 2 and 3.
