### ISSUE TITLE
standardize script of mol file without rdkit or openbabel

### ISSUE THREAD

**Issue by khoivan88** [mcs07/MolVS#34]
Hi, thank you for this super userful library as well as others (Pubchempy, Chemspipy, CIRPy).

I have a python script for a chemical inventory program (Open Enventory) that scrapes mol files from various websites. The scraping file is doing a pretty good job but a small percentage of the mol files (mostly from pubchem) have explicit hydrogens and I want the mol files to have implicit hydrogens. I have discovered rdkit, and open babel to be able to clean the mol file (convert explixit hydrogens to implicit hydrogens). Your molvs is exactly what I am looking for and more (the `standardize` module).  However,  I want my python scraping code to be more portable and usable for non technical people and I am just looking for a small library or code that can do the "standardize" function without installing rdkit or open babel. 

I was wondering if you might know of such library or maybe you could direct me to some direction.
Thank you very much!

Best regards,

Khoi Van

**Comment by UnixJunkie** [comment]
Doing chemoinformatics without using one of the available toolkits (CDK, OpenBabel or RDKit) is probably a lot of work. And, to program parts of it you will need to be a computational chemist...

**Comment by khoivan88** [comment]
@UnixJunkie Thank you for your info!
