### ISSUE TITLE
Standardizer gets stuck on a molecule

### ISSUE THREAD

**Issue by adlvdl** [mcs07/MolVS#4]
Hi, I have been trying your module to standardize molecules. However it gets stuck with molecule ZINC000100026244. By the stacktrace when I do a keyboard interruption, it seems to get stuck at the reionize step. Is there a way to set a timeout period so that if it gets stuck like this I can just disregard this molecule and continue? 
I put below the bug example and the stacktrace:

from rdkit import Chem
import molvs
smi="CCOC(=O)C(=O)[CH-]C#N"
s = molvs.Standardizer()
mol=Chem.MolFromSmiles(smi)
mol = s.standardize(mol)

---------------------------------------------------------------------------
KeyboardInterrupt                         Traceback (most recent call last)
<ipython-input-3-6273a38a73f6> in <module>()
      2 s = molvs.Standardizer()
      3 mol=Chem.MolFromSmiles(smi)
----> 4 mol = s.standardize(mol)
      5 print(Chem.MolToSmiles(mol, True))

C:\Software\Miniconda\lib\site-packages\molvs\standardize.py in standardize(self, mol)
     97         mol = self.disconnect_metals(mol)
     98         mol = self.normalize(mol)
---> 99         mol = self.reionize(mol)
    100         Chem.AssignStereochemistry(mol, force=True, cleanIt=True)
    101         # TODO: Check this removes symmetric stereocenters

C:\Software\Miniconda\lib\site-packages\molvs\charge.py in __call__(self, mol)
    152     def __call__(self, mol):
    153         """Calling a Reionizer instance like a function is the same as calling its reionize(mol) method."""
--> 154         return self.reionize(mol)
    155 
    156     def reionize(self, mol):

C:\Software\Miniconda\lib\site-packages\molvs\charge.py in reionize(self, mol)
    195 
    196         while True:
--> 197             ppos, poccur = self._strongest_protonated(mol)
    198             ipos, ioccur = self._weakest_ionized(mol)
    199             if ioccur and poccur and ppos < ipos:

C:\Software\Miniconda\lib\site-packages\molvs\charge.py in _strongest_protonated(self, mol)
    211     def _strongest_protonated(self, mol):
    212         for position, pair in enumerate(self.acid_base_pairs):
--> 213             for occurrence in mol.GetSubstructMatches(pair.acid):
    214                 return position, occurrence
    215         return None, None

KeyboardInterrupt:

**Comment by mcs07** [comment]
Thanks for the bug report.

This should now be fixed - there was a bug in the patterns that are used to decide whether the ionised atom should be changed, resulting in an infinite loop.

Run `pip install -U molvs` to update to the latest version.

**Comment by adlvdl** [comment]
Yes, with the update the example now completes. However a new molecule (ZINC000060321958) that previously finished now is giving problems. Like before I paste the example and traceback.

smi="C[N+]1=C[CH-]N(C(=N)N)/C1=C/[N+](=O)[O-]"
s = molvs.Standardizer()
mol=Chem.MolFromSmiles(smi)
mol = s.standardize(mol)

---------------------------------------------------------------------------
StandardizeError                          Traceback (most recent call last)
<ipython-input-5-59f21c2beaab> in <module>()
      2 s = molvs.Standardizer()
      3 mol=Chem.MolFromSmiles(smi)
----> 4 mol = s.standardize(mol)
      5 print(Chem.MolToSmiles(mol, True))

C:\Software\Miniconda\lib\site-packages\molvs\standardize.py in standardize(self, mol)
     97         mol = self.disconnect_metals(mol)
     98         mol = self.normalize(mol)
---> 99         mol = self.reionize(mol)
    100         Chem.AssignStereochemistry(mol, force=True, cleanIt=True)
    101         # TODO: Check this removes symmetric stereocenters

C:\Software\Miniconda\lib\site-packages\molvs\charge.py in __call__(self, mol)
    153     def __call__(self, mol):
    154         """Calling a Reionizer instance like a function is the same as calling its reionize(mol) method."""
--> 155         return self.reionize(mol)
    156 
    157     def reionize(self, mol):

C:\Software\Miniconda\lib\site-packages\molvs\charge.py in reionize(self, mol)
    200             if ioccur and poccur and ppos < ipos:
    201                 if poccur[-1] == ioccur[-1]:
--> 202                     raise StandardizeError('Reionizer entered an infinite loop! Please report as a MolVS bug.')
    203                 log.info('Moved proton from %s to %s', self.acid_base_pairs[ppos].name, self.acid_base_pairs[ipos].name)
    204                 patom = mol.GetAtomWithIdx(poccur[-1])

StandardizeError: Reionizer entered an infinite loop! Please report as a MolVS bug.

**Comment by mcs07** [comment]
Sorry for dropping this - I hope this is now fixed with v0.0.9.

Let me know if there are still any problems.
