### ISSUE TITLE
Problem with __repr__ method of TautomerTransform class

### ISSUE THREAD

**Issue by jose-manuel** [mcs07/MolVS#7]
Dear Matt, 
installing molvs with pip runs successfully on my Ubuntu desktop. 
I find this package great and very useful!
However, when I try to print the help for the tautomer module in python console, I get the attached error:
[molvs_tautomer_error.txt](https://github.com/mcs07/MolVS/files/776637/molvs_tautomer_error.txt)

I can fix this on my git clone by removing one {!r} from the __repr__ method in the molvs.tautomer.TautomerTransform class (line 63) : 
return 'TautomerTransform({!r}, {!r}, {!r}, {!r}, {!r})'.format(self.name, self.tautomer_str, self.bonds, self.charges)

Cheers, 
Jose Manuel

**Comment by mcs07** [comment]
Thanks, fix will be in the next release!
